services:
  vault:
    image: hashicorp/vault:latest
  ports:
  - "8200:8200"
  environment:
    VAULT_DEV_ROOT_TOKEN_ID: myroot
    VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
  command: vault server -dev -dev-listen-address=0.0.0.0:8200